---
title: "Tutorial 2"
author: "Iz Leitch"
format: pdf
---
```{r}
#this loads libraries
#|echo : FALSE
library(tidyverse)
library(janitor)
library(opendatatoronto)
library(dplyr)
library(scales)
```


## Introduction

This is the paper about rentsafe toronto housing scores



## Running Code

```{r}
#this loads data from the raw data file
#| echo: FALSE
data <- 
  read.csv(here::here("inputs/data/raw_data.csv"))

#This turns SCORE, YEAR_EVALUATED, and YEAR_BUILT into numeric and adds them to the dataset
data <- 
  data |>
  mutate(score = as.numeric(SCORE),
         year_eval = as.numeric(YEAR_EVALUATED),
         year_built = as.numeric(YEAR_BUILT))
```

```{r}
# Graphing score by Year, Property type: Private
#| echo: false

data_average_property_type_private <-
  data |>
  filter(PROPERTY_TYPE == "PRIVATE") |>
  group_by(year_eval) |>
  summarise(mean = mean(score / 100))

data |>
  filter(PROPERTY_TYPE == "PRIVATE")|>
  ggplot(aes(x = year_eval, 
             y = score / 100)) + 
  scale_y_continuous(labels = percent_format(), 
                      limits = c(0, 1)) +
  geom_count(aes(color = "red")) +
  geom_line(data = data_average_property_type_private, aes(x = year_eval, y = mean)) + 
  labs(
    title = "Changes in Score of Private Housing over a Period of 5 Years",
    x = "Year", 
    y = "Score Evaluations in Percent",
    color = ""
  )
  
```
```{r}
# Graphing score by Year, Property type: Social Housing
#| echo: false

data_average_property_type_social <-
  data |>
  filter(PROPERTY_TYPE == "SOCIAL HOUSING") |>
  group_by(year_eval) |>
  summarise(mean = mean(score / 100))

data |>
  filter(PROPERTY_TYPE == "SOCIAL HOUSING")|>
  ggplot(aes(x = year_eval, 
             y = score / 100)) + 
  scale_y_continuous(labels = percent_format(), 
                      limits = c(0, 1)) +
  geom_count(aes(color="red")) +
  geom_line(data = data_average_property_type_social, aes(x = year_eval, y = mean)) + 
  labs(
    title = "Changes in Score of Social Housing over a Period of 5 Years",
    x = "Year", 
    y = "Score Evaluations in Percent",
  )
```

```{r}
#Graphing score by year of evaluation, Property type:TCHC
#| echo: false

data_average_property_type_tchc <-
  data |>
  filter(PROPERTY_TYPE == "TCHC") |>
  group_by(year_eval) |>
  summarise(mean = mean(score / 100))

data |>
  filter(PROPERTY_TYPE == "TCHC")|>
  ggplot(aes(x = year_eval, 
             y = score / 100)) + 
  scale_y_continuous(labels = percent_format(), 
                      limits = c(0, 1)) +
  geom_count(aes(color="red")) +
  geom_line(data = data_average_property_type_tchc, aes(x = year_eval, y = mean)) + 
  labs(
    title = "Changes in Score of Social Housing over a Period of 5 Years",
    x = "Year", 
    y = "Score Evaluations in Percent",
  )


```

```{r}
# Graphing score by year of evaluation: All Property types
#| echo: false

data_average_property_type <-
  data |>
  group_by(year_eval) |>
  summarise(mean = mean(score / 100))

data |>
  ggplot(aes(x = year_eval, 
             y = score / 100)) + 
  scale_y_continuous(labels = percent_format(), 
                      limits = c(0, 1)) +
  geom_count(aes(color="red")) +
  geom_line(data = data_average_property_type, aes(x = year_eval, y = mean)) + 
  labs(
    title = "Changes in Score of Social Housing over a Period of 5 Years",
    x = "Year", 
    y = "Score Evaluations in Percent",
  )

```



## References

